require: rubocop-rails

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
    # rubocopで2件反応する。修正不可の為、rubocopの対象範囲から除外。
    - "db/migrate/20200720082846_create_active_storage_tables.active_storage.rb"
    - "node_modules/**/*"
    - "bin/*"

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
